//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cowbase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cowbase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap activesync {
            get {
                object obj = ResourceManager.GetObject("activesync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE cattle
        ///(
        ///ean						NCHAR(14) NOT NULL PRIMARY KEY,	
        ///birthdate				DATETIME,
        ///sex						INT,		
        ///stock					INT,
        ///weight					NUMERIC(15,5),
        ///passno					NCHAR(10),
        ///fstownralias			NCHAR(24),
        ///docin					INT NOT NULL,
        ///docout					INT,
        ///buyprice				NUMERIC(15,4),
        ///myprice                 NUMERIC(15,4),
        ///buystock				INT,
        ///buyweight				NUMERIC(15,5),
        ///action					NCHAR NOT NULL,
        ///outgrp					INT,
        ///ingrp					INT,
        ///termbuystock			INT,
        ///termbuyweight			NUMERIC(15,5),
        ///termsellstock			INT,
        ///termsellweight			N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CATTLESQL {
            get {
                return ResourceManager.GetString("CATTLESQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE hents
        ///(
        ///hentid					INT PRIMARY KEY,
        ///alias					NVARCHAR(24) NOT NULL,
        ///name					NVARCHAR(64) NOT NULL,
        ///zip 					NVARCHAR(10),
        ///city					NVARCHAR(48),
        ///street					NVARCHAR(48),
        ///pobox					NVARCHAR(10),
        ///arimrno					NCHAR(14),
        ///plate					NVARCHAR(16),
        ///henttype				INT NOT NULL,
        ///
        ///
        ///CONSTRAINT henttypes_fk FOREIGN KEY (henttype) REFERENCES henttypes(henttypeid)
        ///);.
        /// </summary>
        internal static string HENTSSQL {
            get {
                return ResourceManager.GetString("HENTSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE henttypes
        ///(
        ///henttypeid			INT PRIMARY KEY,
        ///henttypename		NVARCHAR(32)  NOT NULL
        ///);
        ///.
        /// </summary>
        internal static string HENTTYPESSQL {
            get {
                return ResourceManager.GetString("HENTTYPESSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO henttypes(henttypeid,henttypename) VALUES(1,&apos;Firma&apos;);
        ///INSERT INTO henttypes(henttypeid,henttypename) VALUES(2,&apos;Indywidualny&apos;);
        ///.
        /// </summary>
        internal static string HENTTYPESSQL_DEF {
            get {
                return ResourceManager.GetString("HENTTYPESSQL_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE indocs
        ///(
        ///hent					INT NOT NULL,
        ///docdate					DATETIME NOT NULL,
        ///plateno					NVARCHAR(16) NOT NULL,
        ///loaddate				DATETIME NOT NULL,
        ///docno					INT PRIMARY KEY,
        ///reason					INT NOT NULL,
        ///action					NCHAR NOT NULL,
        ///hasmorecows				INT NOT NULL,
        ///
        ///CONSTRAINT deliver_fk 	 	 FOREIGN KEY (hent)     REFERENCES hents(hentid),
        ///CONSTRAINT inreason_fk	 	 FOREIGN KEY (reason)     REFERENCES inoutreasons(reasonid)
        ///);.
        /// </summary>
        internal static string INDOCSSQL {
            get {
                return ResourceManager.GetString("INDOCSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE outdocs
        ///(
        ///hent					INT NOT NULL,
        ///docdate					DATETIME NOT NULL,
        ///plateno					NVARCHAR(16) NOT NULL,
        ///loaddate				DATETIME NOT NULL,
        ///docno					INT PRIMARY KEY,
        ///reason					INT NOT NULL,
        ///action					NCHAR NOT NULL,
        ///
        ///CONSTRAINT buyer_fk 	 	 FOREIGN KEY (hent)     REFERENCES hents(hentid),
        ///CONSTRAINT outreason_fk	 	 FOREIGN KEY (reason)     REFERENCES inoutreasons(reasonid)
        ///);.
        /// </summary>
        internal static string OUTDOCSSQL {
            get {
                return ResourceManager.GetString("OUTDOCSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE inoutreasons			
        ///(
        ///reasonid				INT PRIMARY KEY,
        ///reasoncode				NVARCHAR(5) NOT NULL,
        ///reasonname				NVARCHAR(48),
        ///inoutreason				INT NOT NULL
        ///);
        ///.
        /// </summary>
        internal static string REASONSSQL {
            get {
                return ResourceManager.GetString("REASONSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO inoutreasons(reasonid,reasoncode,reasonname,inoutreason) VALUES(1,&apos;UR&apos;,&apos;URODZENIE&apos;,1);
        ///INSERT INTO inoutreasons(reasonid,reasoncode,reasonname,inoutreason) VALUES(2,&apos;K&apos;,&apos;KUPNO&apos;,1);
        ///INSERT INTO inoutreasons(reasonid,reasoncode,reasonname,inoutreason) VALUES(3,&apos;I&apos;,&apos;IMPORT&apos;,1);
        ///INSERT INTO inoutreasons(reasonid,reasoncode,reasonname,inoutreason) VALUES(4,&apos;E&apos;,&apos;EXPORT&apos;,-1);
        ///INSERT INTO inoutreasons(reasonid,reasoncode,reasonname,inoutreason) VALUES(5,&apos;SU&apos;,&apos;SPRZEDAŻ W CELU UBOJU&apos;,-1);
        ///INSERT INTO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REASONSSQL_DEF {
            get {
                return ResourceManager.GetString("REASONSSQL_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE stocks			
        ///(
        ///stockcode				NVARCHAR(8) NOT NULL UNIQUE,
        ///predefsex				INT,
        ///stockid					INT PRIMARY KEY
        ///);.
        /// </summary>
        internal static string STOCKSSQL {
            get {
                return ResourceManager.GetString("STOCKSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE synclock		
        ///(
        ///lockid					INT PRIMARY KEY,
        ///locktime				DATETIME,
        ///lock					INT NOT NULL
        ///);.
        /// </summary>
        internal static string SYNCLOCKSQL {
            get {
                return ResourceManager.GetString("SYNCLOCKSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO synclock(lockid,locktime,lock) VALUES(1,GETDATE(),0);
        ///.
        /// </summary>
        internal static string SYNCLOCKSQL_DEF {
            get {
                return ResourceManager.GetString("SYNCLOCKSQL_DEF", resourceCulture);
            }
        }
    }
}
